export const nodeData = [
  { id:"R-siewlater",  zone:"Siew Later Restaurant", status:"normal", hazard:null, temp:27, crowd:0, x:120.1, y:219.1 },
  { id:"R-bawangtea",  zone:"BawangTea",              status:"normal", hazard:null, temp:27, crowd:0, x:205.7, y:219.1 },
  { id:"R-chillzone",  zone:"Chill Zone",             status:"normal", hazard:null, temp:27, crowd:0, x:282.1, y:130.5 },
  { id:"R-emptyspace", zone:"Empty Space",            status:"normal", hazard:null, temp:27, crowd:0, x:380.6, y:219.1 },
  { id:"R-thairelax",  zone:"Thai Relax Massage",     status:"normal", hazard:null, temp:27, crowd:0, x:455.8, y:219.1 },
  { id:"R-femalewash", zone:"Female Washroom",        status:"normal", hazard:null, temp:27, crowd:0, x:660.2, y: 86.8 },
  { id:"R-malewash",   zone:"Male Washroom",          status:"normal", hazard:null, temp:27, crowd:0, x:660.2, y:167.4 },
  { id:"R-alibarber",  zone:"Ali Barber",             status:"normal", hazard:null, temp:27, crowd:0, x:640.5, y:357.0 },
  { id:"R-publicrec",  zone:"Public Recipe",          status:"normal", hazard:null, temp:27, crowd:0, x:325.8, y:375.4 },
  { id:"R-mamadini",   zone:"Mamadini",               status:"normal", hazard:null, temp:27, crowd:0, x:396.6, y:375.4 },
  { id:"R-meating",    zone:"Meating Room",           status:"normal", hazard:null, temp:27, crowd:0, x:117.6, y:464.1 },
  { id:"R-baskin",     zone:"Baskin Batman",          status:"normal", hazard:null, temp:27, crowd:0, x:117.6, y:576.7 },
  { id:"R-custsvc",    zone:"Customer Service",       status:"normal", hazard:null, temp:27, crowd:0, x:272.2, y:510.8 },
  { id:"R-msdiy",      zone:"MS. DIY",                status:"normal", hazard:null, temp:27, crowd:0, x:474.8, y:501.6 },
  { id:"R-sofasogood", zone:"SofaSoGood",             status:"normal", hazard:null, temp:27, crowd:0, x:582.0, y:501.6 },
  { id:"R-readme",     zone:"ReadMe Bookstore",       status:"normal", hazard:null, temp:27, crowd:0, x:700.9, y:501.6 },
  { id:"EXIT-1", zone:"Exit 1 (West)",           status:"normal", hazard:null, temp:27, crowd:0, x: 15.4, y:331.7 },
  { id:"EXIT-2", zone:"Exit 2 (North-Center)",   status:"normal", hazard:null, temp:27, crowd:0, x:282.1, y: 12.3 },
  { id:"EXIT-3", zone:"Exit 3 (North-Right)",    status:"normal", hazard:null, temp:27, crowd:0, x:582.0, y: 12.3 },
  { id:"EXIT-4", zone:"Exit 4 (East)",           status:"normal", hazard:null, temp:27, crowd:0, x:751.4, y:469.0 },
  { id:"EXIT-5", zone:"Exit 5 / Assembly Point", status:"normal", hazard:null, temp:27, crowd:0, x:205.7, y:675.8 },
];

export const eventLog = [
  { time:"INIT", msg:"Lumina system online — all subsystems nominal",           level:"success" },
  { time:"INIT", msg:"DYN-A* routing engine loaded — 16 rooms, 5 exits",        level:"info"    },
  { time:"INIT", msg:"Thermal classifier ready — Z-score baseline calibrating", level:"info"    },
  { time:"INIT", msg:"FFT classifier ready — listening for 520Hz FACP tone",    level:"info"    },
  { time:"INIT", msg:"MQTT broker connected — awaiting sensor telemetry",       level:"info"    },
];
